export const TODO_LIST_FETCH_REQUEST = "TODO_LIST_FETCH_REQUEST";
export const TODO_LIST_FETCH_FAILURE = "TODO_LIST_FETCH_FAILURE";
export const TODO_UPDATE_REQUEST = "TODO_UPDATE_REQUEST";
export const TODO_UPDATE_FAILURE = "TODO_UPDATE_FAILURE";
export const TODO_ADD_REQUEST = "TODO_ADD_REQUEST";
export const TODO_ADD_FAILURE = "TODO_ADD_FAILURE";

